Storage/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace Storage.Models
{
    public class InvoiceModel
    {
        public InvoiceModel()
        {
            Supplier = new ClientModel();
            Recipient = new ClientModel();

            Products = new List<ProductsInInvoiceModel>();
        }

        public int ID { get; set; }
        public ClientModel Supplier { get; set; }
        public ClientModel Recipient { get; set; }
        public List<ProductsInInvoiceModel> Products { get; set; }
        [DisplayName("Дата")]
        public DateTime Date { get; set; }
        public string Type { get; set; }
        [DisplayName("Номер")]
        public int Number { get; set; }
        public decimal MasterTotal { get; set; }
        public string PriceType { get; set; }
    }

    public class ProductsInInvoiceModel
    {
        public int ID { get; set; }
        public int ProductID { get; set; }
        public double Quantity { get; set; }
        public decimal Price { get; set; }
        public ProductModel Product { get; set; }
        public int Position { get; set; }
        public decimal Total { get; set; }
    }
}

Storage/ViewModels/InvoiceViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Storage.Models;

namespace Storage.ViewModels
{
    public class InvoiceViewModel
    {
        public InvoiceViewModel()
        {
            InvoiceModel = new InvoiceModel();
            
            Clients = new List<SelectListItem>();
        }

        public InvoiceModel InvoiceModel { get; set; }

        public List<SelectListItem> Clients { get; set; }
        public List<SelectListItem> PriceTypes { get; set; }
    }
}

Storage/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Storage.DAO;
using Storage.Models;
using Storage.ViewModels;

namespace Storage.Controllers
{
    public class InvoiceController : Controller
    {
        //
        // GET: /Invoice/

        public ActionResult Index(string type)
        {
            List<InvoiceModel> list = InvoiceDAO.GetInvoiceList(type);

            ViewBag.Type = type;

            return View(list);
        }

        //
        // GET: /Invoice/Create

        public ActionResult Create(string type)
        {
            ViewBag.Type = type;

            var invoiceModel = new InvoiceModel
                                   {
                                       Number = InvoiceDAO.GetNextInvoiceNumber(type),
                                       Date = DateTime.Now,
                                       Type = type
                                   };

            var clientList = ClientDAO.GetClientList().Select(client => new SelectListItem
                                                                    {
                                                                        Text = client.Name, Value = client.ID.ToString()
                                                                    }).ToList();

            
            return View(new InvoiceViewModel
                            {
                                InvoiceModel = invoiceModel,
                                Clients = clientList,
                                PriceTypes = GetPriceTypes()
                            });
        } 

        //
        // POST: /Invoice/Create

        [HttpPost]
        public ActionResult Create(InvoiceModel invoiceModel)
        {
            try
            {
                InvoiceDAO.SaveInvoice(invoiceModel);

                return RedirectToAction("Index", new { type = invoiceModel.Type });
            }
            catch
            {
                return View();
            }
        }
        
        public ActionResult Print(int id)
        {
            InvoiceModel invoiceModel = InvoiceDAO.GetInvoice(id);

            ViewBag.Type = invoiceModel.Type;

            return View(invoiceModel);
        }

        public ActionResult Edit(int id, string type)
        {
            ViewBag.Type = type;

            var invoiceModel = InvoiceDAO.GetInvoice(id);

            var clientList = ClientDAO.GetClientList().Select(client => new SelectListItem
                                                                    {
                                                                        Text = client.Name, Value = client.ID.ToString()
                                                                    }).ToList();

            return View(new InvoiceViewModel
                            {
                                InvoiceModel = invoiceModel,
                                Clients = clientList,
                                PriceTypes = GetPriceTypes()
                            });
        }

        [HttpPost]
        public ActionResult Edit(InvoiceModel invoiceModel)
        {
            try
            {
                InvoiceDAO.UpdateInvoice(invoiceModel);

                return RedirectToAction("Index", new { type = invoiceModel.Type });
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id, string type)
        {
            InvoiceDAO.DeleteInvoice(id);

            return RedirectToAction("Index", new {type});
        }

        private List<SelectListItem> GetPriceTypes()
        {
            return new List<SelectListItem>
                                        {
                                            new SelectListItem {Value = "RetailPrice", Text = "Цена (розница)"},
                                            new SelectListItem {Value = "ShallowWholesalePrice", Text = "Цена (мелкий опт)"},
                                            new SelectListItem {Value = "WholesalePrice", Text = "Цена (опт)"}
                                        };
        }
    }
}

Storage/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using Storage.DAO;
using Storage.Helpers;
using Storage.Models;
using System.Linq;

namespace Storage.Controllers
{
    public class ProductController : Controller
    {
        //
        // GET: /Product/

        public ActionResult Index()
        {
            var categories = GetCategories();

            categories.Insert(0, new SelectListItem { Value = "-1", Text = "Все" });

            ViewBag.Categories = categories;

            List<ProductModel> list = ProductDAO.GetProductList();

            return View(list);
        }

        //
        // POST: /Product/

        [HttpPost]
        public ActionResult Index(int categoryID, string code, string name)
        {
            List<SelectListItem> categories = GetCategories();

            categories.Insert(0, new SelectListItem { Value = "-1", Text = "Все" });

            foreach (SelectListItem selectListItem in categories)
            {
                if(selectListItem.Value == categoryID.ToString())
                {
                    selectListItem.Selected = true;
                }
            }

            ViewBag.Categories = categories;
            ViewBag.Code = code;
            ViewBag.Name = name;

            List<ProductModel> list = ProductDAO.GetProductListByFilter(categoryID, code, name);

            return View(list);
        }

        //
        // GET: /Product/Details/5

        public ActionResult Details(int id)
        {
            var product = ProductDAO.GetProduct(id);

            return View(product);
        }

        //
        // GET: /Product/Create

        public ActionResult Create()
        {
            ViewBag.Categories = GetCategories();

            return View();
        }

        //
        // POST: /Product/Create

        [HttpPost]
        public ActionResult Create(ProductModel productModel)
        {
            try
            {
                ProductDAO.CreateProduct(productModel);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Product/Edit/5

        public ActionResult Edit(int id)
        {
            var product = ProductDAO.GetProduct(id);

            List<SelectListItem> categories = GetCategories();

            foreach (SelectListItem selectListItem in categories)
            {
                if (product.Category.ID.HasValue && selectListItem.Value == product.Category.ID.ToString())
                {
                    selectListItem.Selected = true;
                }
            }

            ViewBag.Categories = categories;

            return View(product);
        }

        //
        // POST: /Product/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, ProductModel productModel)
        {
            try
            {
                ProductDAO.UpdateProduct(id, productModel);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Product/Delete/5

        public ActionResult Delete(int id)
        {
            var product = ProductDAO.GetProduct(id);

            return View(product);
        }

        //
        // POST: /Product/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, ProductModel productModel)
        {
            try
            {
                ProductDAO.DeleteProduct(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult PriceList()
        {
            var categories = GetCategories();

            categories.Insert(0, new SelectListItem { Value = "-1", Text = "Все" });

            ViewBag.Categories = categories;

            List<ProductModel> list = ProductDAO.GetProductList();

            return View(list);
        }

        [HttpPost]
        public ActionResult PriceList(int categoryID)
        {
            List<SelectListItem> categories = GetCategories();

            categories.Insert(0, new SelectListItem { Value = "-1", Text = "Все" });

            foreach (SelectListItem selectListItem in categories)
            {
                if (selectListItem.Value == categoryID.ToString())
                {
                    selectListItem.Selected = true;
                }
            }

            ViewBag.Categories = categories;

            List<ProductModel> list = ProductDAO.GetProductListByCategory(categoryID);

            return View(list);
        }

        [HttpPost]
        public JsonResult GetProductByCode(string code, string priceType)
        {
            ProductModel productModel = ProductDAO.GetProductByCode(code);

            if (productModel != null)
            {
                decimal price = default(decimal);

                switch (priceType)
                {
                    case "RetailPrice":
                        price = productModel.RetailPrice;
                        break;
                    case "ShallowWholesalePrice":
                        price = productModel.ShallowWholesalePrice;
                        break;
                    case "WholesalePrice":
                        price = productModel.WholesalePrice;
                        break;
                }

                return Json(new
                                {
                                    success = "true",
                                    ID = productModel.ID,
                                    Name = productModel.Name,
                                    Unit = productModel.Unit,
                                    Price = CurrencyHelper.FormatCurrency(price),
                                    Code = code
                                });
            }

            return Json(new { error = "Извините, но по такому коду не найдено ни одного товара." });
        }

        private static List<SelectListItem> GetCategories()
        {
            List<SelectListItem> categories = CategoryDAO.GetCategoryList().Select(c => new SelectListItem
            {
                Value = c.ID.ToString(),
                Text = c.Name
            }).ToList();
            return categories;
        }
    }
}

Storage/Views/Invoice/Create.cshtml
@using Storage.Helpers
@model Storage.ViewModels.InvoiceViewModel

@{
    ViewBag.Title = ViewBag.Type == "Income" ? "Создать Приходную Накладную" : "Создать Расходную Накладную";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/CreateInvoice.js")" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function () {
        InsertFirstRow();

        SetProductCodeEvent('@Url.Action("GetProductByCode", "Product")');
        SetProductQuantityEvent();
        SetDeleteLineEvent();
    });

</script>

@if (ViewBag.Type == "Income")
{
    <h2>Приходная накладная № @Model.InvoiceModel.Number от @Model.InvoiceModel.Date.Day @DateTimeHelper.GetMonthName(Model.InvoiceModel.Date) @Model.InvoiceModel.Date.Year г.</h2>
}
else
{
    <h2>Расходная накладная № @Model.InvoiceModel.Number от @Model.InvoiceModel.Date.Day @DateTimeHelper.GetMonthName(Model.InvoiceModel.Date) @Model.InvoiceModel.Date.Year г.</h2>
}

@using (Html.BeginForm()) {

@Html.HiddenFor(model => model.InvoiceModel.Date)
@Html.HiddenFor(model => model.InvoiceModel.Type)
@Html.HiddenFor(model => model.InvoiceModel.Number)
    
<table class="table">
    <tr>
        <td>
            @Html.LabelFor(model => model.InvoiceModel.Supplier.ID, "Поставщик:")
        </td>
        <td>
            @Html.DropDownListFor(model => model.InvoiceModel.Supplier.ID, Model.Clients)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.InvoiceModel.Recipient.ID, "Получатель:")
        </td>
        <td>
            @Html.DropDownListFor(model => model.InvoiceModel.Recipient.ID, Model.Clients)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.InvoiceModel.PriceType, "Цена:")
        </td>
        <td>
            @Html.DropDownListFor(model => model.InvoiceModel.PriceType, Model.PriceTypes)
        </td>
    </tr>
</table>
<br/>
<table id="invoiceProducts" class="table" width="100%">
    <tr>
        <th style="text-align: center; width: 20px;">
            №
        </th>
        <th style="text-align: center; width: 30px;">
            Код
        </th>
        <th style="text-align: center;">
            Наименование
        </th>
        <th style="text-align: center; width: 20px;">
            Кол.
        </th>
        <th style="text-align: center; width: 50px;">
            Ед.
        </th>
        <th style="text-align: center; width: 52px;">
            Цена
        </th>
        <th style="text-align: center; width: 60px;">
            Сумма
        </th>
        <th style="text-align: center; width: 64px;">
            Действия
        </th>
    </tr>
    <tr>
        <td colspan="6" style="text-align: right; border: 0px;">
            Итого:
        </td>
        <td style="text-align: right; border: 0px;">
            <span class="mastertotal"></span>
        </td>
    </tr>
</table>

<p>
    <input type="submit" value="Сохранить" />
</p>
}

Storage/Views/Invoice/Edit.cshtml
@using Storage.Helpers
@model Storage.ViewModels.InvoiceViewModel

@{
    ViewBag.Title = ViewBag.Type == "Income" ? "Редактировать Приходную Накладную" : "Редактировать Расходную Накладную";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="@Url.Content("~/Scripts/CreateInvoice.js")" type="text/javascript"></script>

<script type="text/javascript">
    $(document).ready(function () {
        SetProductCodeEvent('@Url.Action("GetProductByCode", "Product")');
        SetProductQuantityEvent();
        SetDeleteLineEvent();

        UpdateTable();
        UpdateMasterTotal();

        InsertLastRow();
    });

</script>

@if (ViewBag.Type == "Income")
{
    <h2>Приходная накладная № @Model.InvoiceModel.Number от @Model.InvoiceModel.Date.Day @DateTimeHelper.GetMonthName(Model.InvoiceModel.Date) @Model.InvoiceModel.Date.Year г.</h2>
}
else
{
    <h2>Расходная накладная № @Model.InvoiceModel.Number от @Model.InvoiceModel.Date.Day @DateTimeHelper.GetMonthName(Model.InvoiceModel.Date) @Model.InvoiceModel.Date.Year г.</h2>
}

@using (Html.BeginForm()) {

@Html.HiddenFor(model => model.InvoiceModel.Date)
@Html.HiddenFor(model => model.InvoiceModel.Type)
@Html.HiddenFor(model => model.InvoiceModel.Number)
@Html.HiddenFor(model => model.InvoiceModel.ID)
    
<table class="table">
    <tr>
        <td>
            @Html.LabelFor(model => model.InvoiceModel.Supplier.ID, "Поставщик:")
        </td>
        <td>
            @Html.DropDownListFor(model => model.InvoiceModel.Supplier.ID, Model.Clients)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.InvoiceModel.Recipient.ID, "Получатель:")
        </td>
        <td>
            @Html.DropDownListFor(model => model.InvoiceModel.Recipient.ID, Model.Clients)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.InvoiceModel.PriceType, "Цена:")
        </td>
        <td>
            @Html.DropDownListFor(model => model.InvoiceModel.PriceType, Model.PriceTypes)
        </td>
    </tr>
</table>
<br/>
<table id="invoiceProducts" class="table" width="100%">
    <tr>
        <th style="text-align: center; width: 20px;">
            №
        </th>
        <th style="text-align: center; width: 30px;">
            Код
        </th>
        <th style="text-align: center;">
            Наименование
        </th>
        <th style="text-align: center; width: 20px;">
            Кол.
        </th>
        <th style="text-align: center; width: 50px;">
            Ед.
        </th>
        <th style="text-align: center; width: 52px;">
            Цена
        </th>
        <th style="text-align: center; width: 60px;">
            Сумма
        </th>
        <th style="text-align: center; width: 64px;">
            Действия
        </th>
    </tr>
    @foreach (var product in Model.InvoiceModel.Products)
    {
        int position = Model.InvoiceModel.Products.IndexOf(product);
        
        <tr>
            <td style='text-align: center'>
                <span class='rowNumber'></span>
            </td>
            <td>
                <input id='productCode' class='productCode' type='text' value="@product.Product.Code"/>
                <input class='hiddenProductID' id='InvoiceModel_Products[@position]_ProductID' name='InvoiceModel.Products[@position].ProductID' type='hidden' value='@product.Product.ID' />
            </td>
            <td style='text-align: left'>
                <span id='productName' class='productName'>@product.Product.Name</span>
            </td>
            <td>
                <input id='InvoiceModel_Products[@position]_Quantity' name='InvoiceModel.Products[@position].Quantity' value="@product.Quantity" class='productQuantity' type='text' style='text-align: right'/>
            </td>
            <td style='text-align: left'>
                <span id='productUnit' class='productUnit'>@product.Product.Unit</span>
            </td>
            <td style='text-align: right'>
                <span id='productPrice' class='productPrice'>@CurrencyHelper.FormatCurrency(product.Price)</span>
                <input class='hiddenPrice' id='InvoiceModel_Products[@position]_Price' name='InvoiceModel.Products[@position].Price' type='hidden' value='@product.Price' />
            </td>
            <td style='text-align: right'>
                <span id='total' class='total'>@CurrencyHelper.FormatCurrency(product.Total)</span>
            </td>
            <td style='text-align:center;'>
                <a class='deleteline' href='#'>Удалить</a>
            </td>
        </tr>
    }
    <tr>
        <td colspan="6" style="text-align: right; border: 0px;">
            Итого:
        </td>
        <td style="text-align: right; border: 0px;">
            <span class="mastertotal"></span>
        </td>
    </tr>
</table>

<p>
    <span style="padding-right: 20px">
        <input type="submit" value="Изменить" />
    </span> 
    @Html.ActionLink(ViewBag.Type == "Income" ? "Вернуться к Списку Приходных Накладных" : "Вернуться к Списку Расходных Накладных", "Index", "Invoice", new { type = ViewBag.Type }, null)
</p>
}

Storage/Views/Invoice/Index.cshtml
@using Storage.Helpers
@model IEnumerable<Storage.Models.InvoiceModel>

@{
    ViewBag.Title = ViewBag.Type == "Income" ?  "Список Приходных Накладных" : "Список Расходных Накладных";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if(ViewBag.Type == "Income")
    {
        <h2>Список Приходных Накладных</h2>
    } else
    {
        <h2>Список Расходных Накладных</h2>
    }


<p>
    @Html.ActionLink("Создать Накладную", "Create", "Invoice", new { type = ViewBag.Type }, null)
</p>
<table class="table">
    <tr>
        <th>
            № Накладной
        </th>
        <th>
            Дата
        </th>
        <th>
            Действия
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td style="text-align: center">
            @Html.DisplayFor(modelItem => item.Number)
        </td>
        <td>
            @item.Date.Day @DateTimeHelper.GetMonthName(item.Date) @item.Date.Year г.
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id = item.ID, type = ViewBag.Type }) |
            @Html.ActionLink("Подготовить к Печати", "Print", new { id=item.ID }) |
            @Html.ActionLink("Удалить", "Delete", new { id = item.ID, type = ViewBag.Type }, new { onclick = "return confirm('Вы уверены, что хотите удалить эту накладную?');" })
        </td>
    </tr>
}

</table>

Storage/Views/Invoice/Print.cshtml
@using Storage.Helpers
@model Storage.Models.InvoiceModel

@{
    ViewBag.Title = ViewBag.Type == "Income" ? "Распечатать Приходную Накладную" : "Распечатать Расходную Накладную";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (ViewBag.Type == "Income")
{
    <h2 style="margin-bottom: 0px;">Приходная накладная № @Model.Number от @Model.Date.Day @DateTimeHelper.GetMonthName(Model.Date) @Model.Date.Year г.</h2>
}
else
{
    <h2 style="margin-bottom: 0px;">Расходная накладная № @Model.Number от @Model.Date.Day @DateTimeHelper.GetMonthName(Model.Date) @Model.Date.Year г.</h2>
}

<hr class="printline" />

<div class="print-link" style="margin: 12px 0px 6px 0px">
    <a href="JavaScript:window.print();">@(ViewBag.Type == "Income" ? "Распечатать Приходную Накладную" : "Распечатать Расходную Накладную")</a>
</div>

<table border="0" style="border-collapse: separate; border-spacing:0 10px;" cellspacing="0">
    <tr>
        <td style="padding-right: 60px; vertical-align: top;">
            Поставщик
        </td>
        <td>
            <div>
                <strong>@Model.Supplier.Name</strong>
            </div>
            <div>
                тел. @Model.Supplier.Telephone, @Model.Supplier.Address
            </div>
        </td>
    </tr>
    <tr>
        <td style="padding-right: 60px; vertical-align: top;">
            Получатель
        </td>
        <td>
            <div>
                <strong>@Model.Recipient.Name</strong>
            </div>
            <div>
                тел. @Model.Recipient.Telephone, @Model.Recipient.Address
            </div>
        </td>
    </tr>
</table>
<div style="height: 8px;"></div>
<table class="table" width="100%">
    <tr>
        <th style="text-align: center; width: 20px;">
            №
        </th>
        <th style="text-align: center; width: 42px;">
            Код
        </th>
        <th style="text-align: center;">
            Наименование
        </th>
        <th style="text-align: center; width: 20px;">
            Кол.
        </th>
        <th style="text-align: center; width: 50px;">
            Ед.
        </th>
        <th style="text-align: center; width: 52px;">
            Цена
        </th>
        <th style="text-align: center; width: 60px;">
            Сумма
        </th>
    </tr>

    @foreach (var item in Model.Products)
    {
        <tr>
            <td style='text-align: center'>@item.Position</td>
            <td style='text-align: center'>@item.Product.Code</td>
            <td>@item.Product.Name</td>
            <td style='text-align: right'>@item.Quantity</td>
            <td style='text-align: left'>@item.Product.Unit</td>
            <td style='text-align: right'>@CurrencyHelper.FormatCurrency(item.Price)</td>
            <td style='text-align: right'>@CurrencyHelper.FormatCurrency(@item.Total)</td>
        </tr>
    }
    
    <tr>
        <td colspan="6" style="text-align: right; border: 0px;">
            Итого:
        </td>
        <td style="text-align: right; border: 0px;">
            <strong>@CurrencyHelper.FormatCurrency(Model.MasterTotal)</strong>
        </td>
    </tr>
</table>
<hr class="printline" style="margin-top: 60px; margin-bottom: 20px;"/>
<table border="0" style="border-collapse:collapse; width: 100%" cellspacing="0">
    <tr>
        <td style="width: 80px">
            Отгрузил(а):
        </td>
        <td >
            <hr style="border: 0; color: black; background-color: black; height: 1px; position: relative; top: 10px;"/>
        </td>
        <td style="width: 80px; padding-left: 30px;">
            Получил(а):
        </td>
        <td>
            <hr style="border: 0; color: black; background-color: black; height: 1px; position: relative; top: 10px;"/>
        </td>
    </tr>
</table>